### ISSUE TITLE
[Forge 1.20.1] Accessory Combination glitch when using Curios inventory.

### ISSUE THREAD

**Issue by PlayfulPiano** [Majrusz/MajruszsAccessories#35]
Just went over and combined two dream catcher accessories together, and instead of combining properly, the tooltip of the item has the range instead of properly rolling the item.

This only happens if you combine in your 2x2 crafting grid within your curios inventory keybind from what I can tell.

This is using lib 6.1.8 and accessories 1.3.3, as well as forge 47.2.8.

**Comment by PlayfulPiano** [comment]
Image example of this happening:
![image](https://github.com/Majrusz/MajruszsAccessories/assets/3158887/64a324fd-ae68-4ac7-bb8b-0d736898d4d8)

**Comment by PlayfulPiano** [comment]
some extra info which might be of use:
- happens when shift clicking not clicking normally
- might be related to the recent curios update that allows for container inventories to be closed using the curios inventory keybind, unsure though

**Comment by Majrusz** [comment]
Hello, have you tried using the latest version? I think it should be resolved now

**Comment by PlayfulPiano** [comment]
Can confirm it did not fix on latest of lib/acc.

Steps I did:
- normally put two of the same accessory in my curios inv hotkey's 2x2 crafting grid
- shift click results out of grid
![image](https://github.com/Majrusz/MajruszsAccessories/assets/3158887/d1ecd64c-771b-482c-9db2-1fc53de843a3)

**Comment by PlayfulPiano** [comment]
(doing the same but regular clicking instead of shift clicking the result out of the crafting grid does not cause the reported bug)

**Comment by JTAhlbrecht** [comment]
Any update on this issue? I'm seeing it in the current version for 1.19.2 and otherwise adore the mod. Thank you for your work!

**Comment by ArtOfCombat** [comment]
Glitches even when clicking in a crafting table now.
